language: python
python:
  - "3.6"
install: "pip install mkdocs"

jobs:
  include:
    - stage: test
      script: ./tests/test_docs.sh
    - stage: deploy
      script: mkdocs gh-deploy
      on:
        branch: master
