language: python
python:
  - "3.6"
install: "pip install -r docs_requirements.txt"

jobs:
  include:
    # Removed tests becaus python and node can't be installed together
    # TODO: Change test_docs.sh to use python script instead of node one.
    # - stage: test
    #   language: python
    #   python:
    #     - "2.7"
    #   install: ""
    #   script: ./tests/test_docs.sh
    - stage: deploy
      script: ./utils/docs_deploy.sh
      on:
        branch: master
